# Generated by Django 5.1.6 on 2025-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
